# Generated by Django 4.0.4 on 2022-05-27 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data', models.DateField(verbose_name='Data')),
                ('abertura', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Abertura')),
                ('fechamento', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Fechamento')),
                ('minimo', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Mínima')),
                ('maxima', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Máxima')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ValuRisk',
                'verbose_name_plural': 'ValuRisks',
                'ordering': ['data'],
            },
        ),
    ]
