# Generated by Django 4.0.4 on 2022-05-28 04:55

from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='image',
            field=models.ImageField(blank=True, default='images/User1.jpg', upload_to=usuario.models.get_file_path),
        ),
    ]
